# Generated by Django 2.2.3 on 2019-07-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logicgame', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mygame',
            old_name='gameType',
            new_name='gameNum',
        ),
    ]
