# Generated by Django 2.2.3 on 2019-07-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logicgame', '0002_auto_20190728_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mygame',
            name='gameNum',
        ),
    ]
