# Generated by Django 2.2.3 on 2019-07-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logicgame', '0003_remove_mygame_gamenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
